bugfix
jj@GROSSER-DELL:/mnt/c/Users/Joachim/Desktop/typescript.telegram-bot-api$ npx tsc ads.ts
ads.ts:175:64 - error TS2367: This condition will always return 'false' since the types 'EType.CONSTRUCTOR' and 'EType.BOTH' have no overlap.

175                             } else if (type == EType.SETTER || type == EType.BOTH) {
                                                                   ~~~~~~~~~~~~~~~~~~


Found 1 error.